apiVersion: v1
kind: Pod
metadata:
  name: nginx-declarative
  labels:
    app: my-website
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
