apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-test
  template:
    metadata:
      labels:
        app: secret-test
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent  # Используем локальный образ
        # Выводим секрет в лог (В РЕАЛЬНОСТИ ТАК ДЕЛАТЬ НЕЛЬЗЯ, ЭТО ТОЛЬКО ДЛЯ УЧЕБЫ!)
        command: ["/bin/sh", "-c", "while true; do echo Пароль из секрета: $MY_DB_PASS; sleep 5; done"]
        env:
          - name: MY_DB_PASS              # Имя переменной внутри контейнера
            valueFrom:
              secretKeyRef:
                name: app-secret          # Имя нашего Secret
                key: DB_PASSWORD          # Ключ внутри Secret